version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.2
    - 3.11.0
    - 3.9.1
  - dependency-name: react-dom
    versions:
    - 17.0.2
  - dependency-name: react
    versions:
    - 17.0.2
  - dependency-name: gatsby-plugin-mdx
    versions:
    - 1.10.0
    - 1.9.0
    - 2.0.1
    - 2.1.0
    - 2.2.0
    - 2.3.0
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.0.0
    - 12.0.1
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: "@fontsource/ubuntu"
    versions:
    - 4.2.1
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.0.0
    - 12.0.1
  - dependency-name: gatsby-plugin-netlify
    versions:
    - 2.11.0
  - dependency-name: gatsby-remark-images
    versions:
    - 3.10.0
    - 3.11.0
  - dependency-name: gatsby-source-filesystem
    versions:
    - 2.10.0
    - 2.11.0
  - dependency-name: "@bugsnag/js"
    versions:
    - 7.7.0
  - dependency-name: gatsby-cli
    versions:
    - 2.18.0
    - 2.19.0
  - dependency-name: gatsby-plugin-offline
    versions:
    - 3.10.0
    - 3.9.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.9.0
  - dependency-name: gatsby-remark-smartypants
    versions:
    - 2.9.0
